name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
on: push
jobs:
  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: RalfG/python-wheels-manylinux-build@v0.4.2
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38m cp39-cp39m cp310-cp310m'
          # build-requirements: ''
          # system-packages: ''
          # pre-build-command: 'sh pre-build-script.sh'
          # package-path: ''
          # pip-wheel-args: '-w ./dist --no-deps'